---
description: 'Дополнительные сведения о: блок "Catch" никогда не достигается; <exception> обрабатывается выше в одном операторе "try"'
title: Невозможно достичь блок "Catch"; "<exception>" обрабатывается выше в том же операторе Try
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: fc52c21f7a319c26b6ca7128c8d2d781db1a58c1
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/14/2021
ms.locfileid: "100473025"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a><span data-ttu-id="1f113-103">Невозможно достичь блок "Catch"; "\<exception>" обрабатывается выше в том же операторе Try</span><span class="sxs-lookup"><span data-stu-id="1f113-103">'Catch' block never reached; \<exception> handled above in the same 'Try' statement</span></span>

<span data-ttu-id="1f113-104">Блок `Catch` в коде недоступен, так как он обрабатывается в предыдущем блоке `Try` .</span><span class="sxs-lookup"><span data-stu-id="1f113-104">A `Catch` block in the code cannot be reached because it is handled in a preceding `Try` block.</span></span>  
  
<span data-ttu-id="1f113-105">По умолчанию данное сообщение является предупреждением.</span><span class="sxs-lookup"><span data-stu-id="1f113-105">By default, this message is a warning.</span></span> <span data-ttu-id="1f113-106">Дополнительные сведения о сокрытии предупреждений и обработке предупреждений как ошибок см. в разделе [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).</span><span class="sxs-lookup"><span data-stu-id="1f113-106">For more information about hiding warnings or treating warnings as errors, see [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).</span></span>
  
 <span data-ttu-id="1f113-107">**Идентификатор ошибки:** BC42031</span><span class="sxs-lookup"><span data-stu-id="1f113-107">**Error ID:** BC42031</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="1f113-108">Исправление ошибки</span><span class="sxs-lookup"><span data-stu-id="1f113-108">To correct this error</span></span>  
  
- <span data-ttu-id="1f113-109">Удалите лишний оператор.</span><span class="sxs-lookup"><span data-stu-id="1f113-109">Remove the redundant statement.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="1f113-110">См. также раздел</span><span class="sxs-lookup"><span data-stu-id="1f113-110">See also</span></span>

- [<span data-ttu-id="1f113-111">Использование блока try/catch для перехвата исключений</span><span class="sxs-lookup"><span data-stu-id="1f113-111">How to use the try/catch block to catch exceptions</span></span>](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [<span data-ttu-id="1f113-112">Использование обработчиков исключений с пользовательской фильтрацией</span><span class="sxs-lookup"><span data-stu-id="1f113-112">Using User-Filtered Exception Handlers</span></span>](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [<span data-ttu-id="1f113-113">Оператор Try...Catch...Finally</span><span class="sxs-lookup"><span data-stu-id="1f113-113">Try...Catch...Finally Statement</span></span>](../language-reference/statements/try-catch-finally-statement.md)
